#!/usr/bin/env python3
"""
Utility module for adding generation footers to HTML visualizations.
Provides consistent "How This Was Generated" footer for all visualization files.
"""

from datetime import datetime


def get_footer_css() -> str:
    """Return CSS styles for the generation footer."""
    return """
        .generation-footer {
            margin-top: 30px;
            padding: 20px;
            background: white;
            border-radius: 8px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            border-top: 3px solid #4299e1;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
        }
        .generation-footer h4 {
            font-size: 0.9rem;
            color: #2d3748;
            margin: 0 0 12px 0;
            font-weight: 600;
        }
        .generation-info {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 12px;
        }
        .info-item {
            font-size: 0.8rem;
            color: #4a5568;
        }
        .info-item strong {
            color: #2d3748;
        }
        .info-item a {
            color: #4299e1;
            text-decoration: none;
        }
        .info-item a:hover {
            text-decoration: underline;
        }
        .info-item code {
            background: #edf2f7;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: 'SF Mono', Consolas, monospace;
            font-size: 0.75rem;
        }
    """


def get_footer_html(
    script_name: str,
    data_source: str = "data/repos.json",
    github_path: str | None = None,
) -> str:
    """
    Generate the HTML footer for a visualization.

    Args:
        script_name: Name of the generating script (e.g., "create_landing_page_viz.py")
        data_source: Primary data source file (e.g., "data/repos.json")
        github_path: Optional path on GitHub for source code link

    Returns:
        HTML string for the footer
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if github_path is None:
        github_path = f"scripts/{script_name}"

    github_url = f"https://github.com/Digital-AI-Finance/org-dashboard/blob/main/{github_path}"

    return f"""
    <div class="generation-footer">
        <h4>How This Page Was Generated</h4>
        <div class="generation-info">
            <div class="info-item">
                <strong>Method:</strong> Auto-generated by Python
            </div>
            <div class="info-item">
                <strong>Script:</strong> <code>scripts/{script_name}</code>
            </div>
            <div class="info-item">
                <strong>Data Source:</strong> <code>{data_source}</code>
            </div>
            <div class="info-item">
                <strong>Generated:</strong> {timestamp}
            </div>
            <div class="info-item">
                <strong>Source Code:</strong>
                <a href="{github_url}" target="_blank">View on GitHub</a>
            </div>
            <div class="info-item">
                <strong>Process:</strong> GitHub API -> JSON -> Python -> HTML
            </div>
        </div>
    </div>
    """


def inject_footer_into_html(
    html_content: str,
    script_name: str,
    data_source: str = "data/repos.json",
) -> str:
    """
    Inject footer into existing HTML content.

    Inserts footer CSS into <head> and footer HTML before </body>.

    Args:
        html_content: Original HTML string
        script_name: Name of the generating script
        data_source: Primary data source file

    Returns:
        Modified HTML with footer injected
    """
    footer_css = get_footer_css()
    footer_html = get_footer_html(script_name, data_source)

    # Inject CSS before </head>
    if "</head>" in html_content:
        html_content = html_content.replace(
            "</head>",
            f"<style>{footer_css}</style>\n</head>",
        )
    elif "</style>" in html_content:
        # If no </head>, try to add after last </style>
        last_style_idx = html_content.rfind("</style>")
        html_content = (
            html_content[: last_style_idx + 8]
            + f"\n<style>{footer_css}</style>"
            + html_content[last_style_idx + 8 :]
        )

    # Inject footer before </body>
    if "</body>" in html_content:
        html_content = html_content.replace(
            "</body>",
            f"{footer_html}\n</body>",
        )

    return html_content
